### PR TITLE
A lot of additions!

### PR DESCRIPTION
**Pull request by lexcyn**
Added a bunch of new items that were announced last week during Microsoft Build - even more to come!

### CODE REVIEW

**Comment by ArminiusTux** [comment]
The more the merrier, however even Microsoft throws everything in one basket - meaning that they not only count native ARM apps but also (successfully) emulated x86/x64 programmes.

[IMAGE ALT TEXT](https://youtu.be/XJup_tRkSaY?t=2223 "Counting Redmond-style...")

**Comment by lexcyn** [comment]
Correct, I'm not adding the emulated versions. Also there are some apps that were announced that don't yet have binaries announced.

**Comment by ArminiusTux** [comment]
Well that reminds me of Barack Obama receiving the Nobel peace prize. 🤔
Shouldn't the achievement precede the accolade? 🧐

**Review by iKineticate — CHANGES_REQUESTED** [review]
### Request Changes

Please change the images to versions with transparent backgrounds. This will help maintain consistent visual appearance across different background colors.😊

- beyondtrustremote.png
- ciscoanyconnect.png
- rsanetwitness.png

[logo.zip](https://github.com/arminask/windows-arm-apps/files/15463382/logo.zip)

**Comment by lexcyn** [comment]
> ### Request Changes
> Please change the images to versions with transparent backgrounds. This will help maintain consistent visual appearance across different background colors.😊
> 
> * beyondtrustremote.png
> * ciscoanyconnect.png
> * rsanetwitness.png
> * mobileiron.png
> 
> [logo.zip](https://github.com/arminask/windows-arm-apps/files/15463382/logo.zip)

I will commit these into a new pull, thanks! I couldn't find some of them,

**Pull request merged**
